#!/usr/bin/env python
import datetime
import subprocess

date = datetime.datetime.utcnow().strftime("%Y.%-m.%-d.%-H%M")
with open('version','w') as version:
   version.write(date)

subprocess.call(["git", "add", "version"])
